### ISSUE TITLE
CannotGetPortalError on publish and on verify

### ISSUE THREAD

**Issue by Lunga001** [senaite/senaite.core#1002]
## Steps to reproduce
This error appears on logs when verifying or publishing an AR.
The AR does get Verified and Published but this error appears on the logs
## Current behavior
`2018-08-23 12:28:48 ERROR ZServerPublisher exception caught
Traceback (most recent call last):
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/ZServer/PubCore/ZServerPublisher.py", line 31, in __init__
    response=b)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 455, in publish_module
    environ, debug, request, response)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/Publish.py", line 276, in publish_module_standard
    if request is not None: request.close()
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/Zope2-2.13.26-py2.7.egg/ZPublisher/BaseRequest.py", line 220, in close
    notify(EndRequestEvent(None, self))
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/zope.event-3.5.2-py2.7.egg/zope/event/__init__.py", line 31, in notify
    subscriber(event)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/event.py", line 24, in dispatch
    zope.component.subscribers(event, None)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/_api.py", line 136, in subscribers
    return sitemanager.subscribers(objects, interface)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/zope.component-3.9.5-py2.7.egg/zope/component/registry.py", line 321, in subscribers
    return self.adapters.subscribers(objects, provided)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/zope.interface-3.6.7-py2.7-linux-x86_64.egg/zope/interface/adapter.py", line 585, in subscribers
    subscription(*objects)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 1578, in EndRequestHandler
    digester(ar, overwrite=True)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 757, in __call__
    data = self._ar_data(ar)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 1031, in _ar_data
    data['managers'] = self._managers_data(ar)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 1448, in _managers_data
    ar_mngrs = self._verifiers_data(ar.UID())
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 1474, in _verifiers_data
    for brain in self.get_analyses(ar_uid):
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/plone.memoize-1.1.2-py2.7.egg/plone/memoize/view.py", line 47, in memogetter
    value = cache[key] = func(*args, **kwargs)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/browser/analysisrequest/publish.py", line 1491, in get_analyses
    return api.search(query, CATALOG_ANALYSIS_LISTING)
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/api/__init__.py", line 646, in search
    catalogs.append(get_tool(catalog))
  File "/home/lunga/instances/senaite-master-zeo/zeocluster/src/senaite.core/bika/lims/api/__init__.py", line 208, in get_tool
    return ploneapi.portal.get_tool(name)
  File "<string>", line 2, in get_tool
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/plone.api-1.8.4-py2.7.egg/plone/api/validation.py", line 77, in wrapped
    return function(*args, **kwargs)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/plone.api-1.8.4-py2.7.egg/plone/api/portal.py", line 118, in get_tool
    return getToolByName(get(), name)
  File "/home/lunga/instances/senaite-master-zeo/buildout-cache/eggs/plone.api-1.8.4-py2.7.egg/plone/api/portal.py", line 82, in get
    'Unable to get the portal object. More info on '
CannotGetPortalError: Unable to get the portal object. More info on http://docs.plone.org/develop/plone.api/docs/api/exceptions.html#plone.api.exc.CannotGetPortalError`
## Expected behavior
Error should not be there

**Comment by ramonski** [comment]
This seems like a duplicate of https://github.com/senaite/senaite.core/issues/856
Please see there for more information @Lunga001

**Comment by Lunga001** [comment]
Ok cool, sorry I missed that will close the issue
