### ISSUE TITLE
Plone instead of Senaite

### ISSUE THREAD

**Issue by witszymanski** [senaite/senaite.core#1996]
## Description

I am not sure where do I make a mistake. I was following the installation guide. It was all without problems until:

```
senaite) senaite@vitia-ThinkPad-T14-Gen-1:~/senaitelims$ which buildout
/home/training/miniconda2/envs/senaite/bin/buildout
/home/senaite/miniconda2/envs/senaite/bin/buildout
-bash: /home/training/miniconda2/envs/senaite/bin/buildout: No such file or directory

```
Then:

```
(senaite) senaite@vitia-ThinkPad-T14-Gen-1:~/senaitelims$ PYTHONHTTPSVERIFY=0 buildout
Error processing line 1 of /home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Getting distribution for 'ZODB3==3.10.5'.
Error processing line 1 of /home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  ModuleNotFoundError: No module named '_distutils_hack'

Remainder of file ignored
Traceback (most recent call last):
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-4ey6fw7k/ZODB3-3.10.5/setup.py", line 34
    print "This version of ZODB requires Python 2.5 or higher"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("This version of ZODB requires Python 2.5 or higher")?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 2308, in main
    setup(
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 412, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 654, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 699, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 884, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1152, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1138, in run_setup
    run_setup(setup_script, args)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 253, in run_setup
    raise
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 166, in save_modules
    saved_exc.resume()
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 141, in resume
    six.reraise(type, exc, self._tb)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/_vendor/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/setuptools/sandbox.py", line 44, in _execfile
    code = compile(script, filename, 'exec')
  File "/tmp/easy_install-4ey6fw7k/ZODB3-3.10.5/setup.py", line 34
    print "This version of ZODB requires Python 2.5 or higher"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("This version of ZODB requires Python 2.5 or higher")?
An error occurred when trying to install /home/senaite/buildout-cache/downloads/dist/ZODB3-3.10.5.tar.gz. Look above this message for any errors that were output by easy_install.
While:
  Installing.
  Getting section instance.
  Initializing section instance.
  Installing recipe plone.recipe.zope2instance.
  Getting distribution for 'ZODB3==3.10.5'.

An internal error occurred due to a bug in either zc.buildout or in a
recipe being used:
Traceback (most recent call last):
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 2174, in main
    getattr(buildout, command)(args)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in install
    [self[part]['recipe'] for part in install_parts]
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 701, in <listcomp>
    [self[part]['recipe'] for part in install_parts]
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1324, in __getitem__
    options._initialize()
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1432, in _initialize
    self.initialize()
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1438, in initialize
    recipe_class = _install_and_load(reqs, 'zc.buildout', entry, buildout)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/buildout.py", line 1381, in _install_and_load
    zc.buildout.easy_install.install(
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 957, in install
    return installer.install(specs, working_set)
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 730, in install
    for dist in self._get_dist(req, ws):
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 574, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/home/senaite/miniconda2/envs/senaite/lib/python3.8/site-packages/zc/buildout/easy_install.py", line 1745, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)

```
I can still make it run:
```

(senaite) senaite@vitia-ThinkPad-T14-Gen-1:~/senaitelims$ bin/instance fg
2022-05-19 12:41:31 INFO ZServer HTTP server started at Thu May 19 12:41:31 2022
	Hostname: 0.0.0.0
	Port: 8080
2022-05-19 12:41:33 INFO Plone OpenID system packages not installed, OpenID support not available
2022-05-19 12:41:35 INFO Zope Ready to handle requests

```

But then it looks like this: 

## Observed behaviour

![image](https://user-images.githubusercontent.com/15866068/169273685-7083b5d2-6822-45fd-9a62-a09459a79d6f.png)

## Expected behaviour

![image](https://user-images.githubusercontent.com/15866068/169275420-aed491f1-2e64-44c8-9653-d77baf694f0d.png)

## Versions

- OS: Linux Ubuntu 22.04

- senaite.core: `master`
- senaite.impress: `master`
- senaite.core.listing: `master`
- senaite.core.supermodel: `master`

What do I do wrong here? 
I'd be happy for any help. 

Witek

**Comment by ramonski** [comment]
Hi @witszymanski,

better place installation related issues here:
https://community.senaite.org/

However, it seems like you used Python 3.8, while SENAITE still requires Python 2.7.x.

Ramon
