### ISSUE TITLE
TestAnalysisRequestRetract is failing in Travis, but working in dev environment

### ISSUE THREAD

**Issue by xispa** [senaite/senaite.core#625]
## Steps to reproduce

See https://travis-ci.org/senaite/senaite.core/builds/336350469

`$ bin/test -m bika.lims -t TestAnalysisRequestRetract`

## Current behavior

```
Error in test test_retract_an_analysis_request (bika.lims.tests.test_AnalysisRequest_retract.TestAnalysisRequestRetract)
Traceback (most recent call last):
  File "/home/travis/build/senaite/senaite.core/eggs/unittest2-0.5.1-py2.7.egg/unittest2/case.py", line 340, in run
    testMethod()
  File "/home/travis/build/senaite/senaite.core/bika/lims/tests/test_AnalysisRequest_retract.py", line 57, in test_retract_an_analysis_request
    wf.doActionFor(analysis, 'submit')
  File "/home/travis/build/senaite/senaite.core/eggs/Products.CMFCore-2.2.10-py2.7.egg/Products/CMFCore/WorkflowTool.py", line 234, in doActionFor
    raise WorkflowException(msg)
WorkflowException: No workflow provides the '${action_id}' action.
```

## Expected behavior

```
$ bin/test -m bika.lims -t TestAnalysisRequestRetract
Running bika.lims.testing.BikaLIMSLayer:Functional tests:
  Set up plone.testing.zca.LayerCleanup in 0.000 seconds.
  Set up plone.testing.z2.Startup in 0.227 seconds.
  Set up plone.app.testing.layers.PloneFixture in 8.348 seconds.
  Set up bika.lims.testing.BikaLIMSLayer in 11.849 seconds.
  Set up bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
  Running:
                
  Ran 1 tests with 0 failures and 0 errors in 1 minutes 4.863 seconds.
Tearing down left over layers:
  Tear down bika.lims.testing.BikaLIMSLayer:Functional in 0.000 seconds.
  Tear down bika.lims.testing.BikaLIMSLayer in 0.005 seconds.
  Tear down plone.app.testing.layers.PloneFixture in 0.061 seconds.
  Tear down plone.testing.z2.Startup in 0.008 seconds.
  Tear down plone.testing.zca.LayerCleanup in 0.002 seconds.
```

**Comment by xispa** [comment]
Closing this one, test is passing again https://travis-ci.org/senaite/senaite.core/builds/336490352
