### ISSUE TITLE
AR Listing Checkboxes keep disabled

### ISSUE THREAD

**Issue by ramonski** [senaite/senaite.core#978]
## Steps to reproduce

Go to the Analysis Requests listing

## Current behavior

Checkboxes stay disabled

## Expected behavior

Checkboxes enable after the async JS call of `allowedTransitionsFor_many` returns with the allowed transitions

## Screenshot (optional)

<img width="394" alt="analysis requests senaite 2018-08-10 11-15-53" src="https://user-images.githubusercontent.com/713193/43951719-1ed537e6-9c94-11e8-9707-d9f1f6a7e1a3.png">

**Comment by ramonski** [comment]
The issue happens on upgraded machines with existing ARs.
The async call for `allowedTransitionsFor_many` returns this:

```json
{"_runtime": 0.018612146377563477, "message": "Cannot get the allowed transitions (guard_sample_prep_transition)", "success": false}
```

**Comment by ramonski** [comment]
Traceback:
```
Traceback (most recent call last):
  File "eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/decorators.py", line 24, in decorator
    return f(*args, **kwargs)
  File "eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py", line 60, in to_json
    return self.dispatch()
  File "eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/api.py", line 54, in dispatch
    return router(self.context, self.request, path)
  File "eggs/plone.jsonapi.core-0.6-py2.7.egg/plone/jsonapi/core/browser/router.py", line 138, in __call__
    return self.view_functions[endpoint](context, request, **values)
  File "senaite.core/bika/lims/jsonapi/allowedtransitionsfor.py", line 59, in allowed_transitions_for_many
    raise BadRequest(msg)
BadRequest: Cannot get the allowed transitions (guard_sample_prep_transition)
```

**Comment by ramonski** [comment]
```python
  80         def getTransitionsFor(self, obj=None, container=None, REQUEST=None):
  81             if type(obj) is type([]):
  82                 return self.flattenTransitions(objs=obj, container=container)
  83             result = {}
  84             chain = self.getChainFor(obj)
  85             for wf_id in chain:
  86                 wf = self.getWorkflowById(wf_id)
  87                 if wf is not None:
  88                     sdef = wf._getWorkflowStateOf(obj)
  89                     if sdef is not None:
  90  ->                     for tid in sdef.transitions:
  91                             tdef = wf.transitions.get(tid, None)
  92                             if tdef is not None and \
  93                                tdef.trigger_type == TRIGGER_USER_ACTION and \
  94                                tdef.actbox_name and \
  95                                wf._checkTransitionGuard(tdef, obj) and \
  96                                not tdef.id in result:
  97                                 result[tdef.id] = {
  98                                         'id': tdef.id,
  99                                         'title': tdef.title,
 100                                         'title_or_id': tdef.title_or_id(),
 101                                         'description': tdef.description,
 102                                         'name': tdef.actbox_name,
 103                                         'url': tdef.actbox_url %
 104                                                {'content_url': obj.absolute_url(),
 105                                                 'portal_url': '',
 106                                                 'folder_url': ''}}
 107             return tuple(result.values())
(Pdb++) sdef.transitions
('prepublish', 'submit', 'sample_prep', 'reject')
```
